# Generated by Django 4.2.2 on 2023-06-21 16:14

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[users.validators.validate_age], verbose_name='Дата рождения'),
        ),
    ]
