# Generated by Django 4.2.2 on 2023-06-24 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[users.validators.validate_age], verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_confirmed',
            field=models.PositiveIntegerField(default=0, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
