# Generated by Django 4.2.2 on 2023-07-01 16:33

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, validators=[users.validators.validate_phone_number], verbose_name='Phone Number'),
        ),
    ]
