# Generated by Django 4.2.2 on 2023-07-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_overview'),
        ('users', '0007_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_movies',
            field=models.ManyToManyField(related_name='favorites_people', to='movies.movie', verbose_name='Favorite Movies'),
        ),
    ]
