# Generated by Django 4.2.2 on 2023-07-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_favorite_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='movie_ratings',
            field=models.JSONField(blank=True, null=True, verbose_name='User Ratings'),
        ),
    ]
