# Generated by Django 4.2.2 on 2023-07-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_movie_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='movie_ratings',
            field=models.JSONField(blank=True, default={}, null=True, verbose_name='User Ratings'),
        ),
    ]
