# Generated by Django 4.2.2 on 2023-07-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_author_alter_comment_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
