# Generated by Django 4.2.2 on 2023-07-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_comment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
