# Generated by Django 4.2.2 on 2023-07-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Title')),
                ('icon_class', models.CharField(blank=True, max_length=255, verbose_name='Icon')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('url', models.CharField(blank=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Footer Social',
                'verbose_name_plural': 'Footer Socials',
            },
        ),
        migrations.CreateModel(
            name='FooterUsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Title')),
                ('icon_class', models.CharField(blank=True, max_length=255, verbose_name='Icon')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('url', models.CharField(blank=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Footer Useful Link',
                'verbose_name_plural': 'Footer Useful Links',
            },
        ),
        migrations.CreateModel(
            name='NaviItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Title')),
                ('icon_class', models.CharField(blank=True, max_length=255, verbose_name='Icon')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('url', models.CharField(blank=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Navi Item',
                'verbose_name_plural': 'Navi Items',
            },
        ),
    ]
