# Generated by Django 4.2.2 on 2023-06-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Not Set'), (1, 'Female'), (2, 'Male'), (3, 'Non Binary')], default=0, verbose_name='Gender'),
        ),
    ]
