# Generated by Django 4.2.2 on 2023-06-22 12:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('genre_id', models.BigIntegerField(verbose_name='TMBD ID')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['genre_id'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('keyword_id', models.BigIntegerField(verbose_name='TMBD ID')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'ordering': ['keyword_id'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('original_language', models.CharField(max_length=255, verbose_name='Oiginal Language')),
                ('is_released', models.BooleanField(default=False, verbose_name='Released')),
                ('release_date', models.DateField(verbose_name='Release Data')),
                ('overview', models.TextField(verbose_name='Description')),
                ('popularity', models.FloatField(blank=True, null=True, verbose_name='Popularity')),
                ('vote_average', models.FloatField(blank=True, null=True, verbose_name='Average Vote')),
                ('tmbd_id', models.BigIntegerField(verbose_name='TMBD ID')),
                ('image', models.ImageField(blank=True, upload_to='movies/%d%m%Y', verbose_name='Image')),
                ('actors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('genres', models.ManyToManyField(to='movies.genre', verbose_name='Genres')),
                ('keywords', models.ManyToManyField(to='movies.keyword', verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['popularity', 'vote_average'],
            },
        ),
    ]
