# Generated by Django 4.2.2 on 2023-06-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='genre_movies', to='movies.genre', verbose_name='Genres'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='keywords',
            field=models.ManyToManyField(related_name='keyword_movies', to='movies.keyword', verbose_name='Keywords'),
        ),
    ]
