# Generated by Django 4.2.2 on 2023-06-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_genres_alter_movie_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Count of Votes'),
        ),
    ]
