# Generated by Django 4.2.2 on 2023-06-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='budjet',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Budjet'),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Runtime'),
        ),
    ]
