# Generated by Django 4.2.2 on 2023-06-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_budjet_movie_runtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-popularity', '-vote_average'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
    ]
