# Generated by Django 4.2.2 on 2023-06-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_tmbd_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actors',
            new_name='actors_list',
        ),
    ]
