# Generated by Django 4.2.2 on 2023-06-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('movies', '0008_rename_actors_movie_actors_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='actor_movies', to='actors.actor', verbose_name='Actors'),
        ),
    ]
