# Generated by Django 4.2.2 on 2023-07-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='likes_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Like Count'),
        ),
    ]
